version: '3.8'

services:
  api:
    build:
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development

  postgres:
    ports:
      - "5432:5432"

  pgadmin:
    ports:
      - "5050:80"